// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox_queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOutboxEntry = `-- name: CreateOutboxEntry :execresult
INSERT INTO outbox (
    transaction_id, 
    topic, 
    payload, 
    status
) VALUES (
    $1, $2, $3, 'PENDING'
) 
ON CONFLICT (txn_id) 
DO NOTHING
`

type CreateOutboxEntryParams struct {
	TransactionID string `json:"transaction_id"`
	Topic         string `json:"topic"`
	Payload       []byte `json:"payload"`
}

func (q *Queries) CreateOutboxEntry(ctx context.Context, arg CreateOutboxEntryParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, createOutboxEntry, arg.TransactionID, arg.Topic, arg.Payload)
}

const getPendingOutboxEntries = `-- name: GetPendingOutboxEntries :many
SELECT 
    transaction_id, 
    topic, 
    payload, 
    status, 
    created_at
FROM outbox
WHERE status = 'PENDING'
ORDER BY created_at ASC
LIMIT 100
FOR UPDATE SKIP LOCKED
`

type GetPendingOutboxEntriesRow struct {
	TransactionID string             `json:"transaction_id"`
	Topic         string             `json:"topic"`
	Payload       []byte             `json:"payload"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetPendingOutboxEntries(ctx context.Context) ([]GetPendingOutboxEntriesRow, error) {
	rows, err := q.db.Query(ctx, getPendingOutboxEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingOutboxEntriesRow
	for rows.Next() {
		var i GetPendingOutboxEntriesRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.Topic,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
