// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox_queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const cleanupOutbox = `-- name: CleanupOutbox :exec
DELETE FROM outbox 
WHERE status = 'SENT' 
AND created_at < NOW() - INTERVAL '24 hours'
`

func (q *Queries) CleanupOutbox(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupOutbox)
	return err
}

const createOutboxEntry = `-- name: CreateOutboxEntry :execresult
INSERT INTO outbox (
    outbox_key, 
    transaction_id, 
    topic, 
    payload, 
    status
) VALUES (
    $1, $2, $3, $4, 'PENDING'
) 
ON CONFLICT (outbox_key) 
DO NOTHING
`

type CreateOutboxEntryParams struct {
	OutboxKey     string `json:"outbox_key"`
	TransactionID string `json:"transaction_id"`
	Topic         string `json:"topic"`
	Payload       []byte `json:"payload"`
}

func (q *Queries) CreateOutboxEntry(ctx context.Context, arg CreateOutboxEntryParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, createOutboxEntry,
		arg.OutboxKey,
		arg.TransactionID,
		arg.Topic,
		arg.Payload,
	)
}

const getPendingOutboxEntries = `-- name: GetPendingOutboxEntries :many
SELECT 
    outbox_key,
    transaction_id, 
    topic, 
    payload, 
    status, 
    created_at
FROM outbox
WHERE status = 'PENDING'
ORDER BY created_at ASC
LIMIT 100
FOR UPDATE SKIP LOCKED
`

func (q *Queries) GetPendingOutboxEntries(ctx context.Context) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, getPendingOutboxEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outbox
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.OutboxKey,
			&i.TransactionID,
			&i.Topic,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOutboxStatus = `-- name: UpdateOutboxStatus :exec
UPDATE outbox
SET status = $2
WHERE outbox_key = $1 
  AND status != $2
`

type UpdateOutboxStatusParams struct {
	OutboxKey string `json:"outbox_key"`
	Status    string `json:"status"`
}

func (q *Queries) UpdateOutboxStatus(ctx context.Context, arg UpdateOutboxStatusParams) error {
	_, err := q.db.Exec(ctx, updateOutboxStatus, arg.OutboxKey, arg.Status)
	return err
}
