// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

type Querier interface {
	CleanupOutbox(ctx context.Context) error
	CreateOutboxEntry(ctx context.Context, arg CreateOutboxEntryParams) (pgconn.CommandTag, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (pgconn.CommandTag, error)
	GetPendingOutboxEntries(ctx context.Context) ([]Outbox, error)
	GetStuckTransactions(ctx context.Context) ([]Transaction, error)
	GetTransaction(ctx context.Context, transactionID string) (Transaction, error)
	IncrementRetryCount(ctx context.Context, transactionID string) error
	UpdateCreditLeg(ctx context.Context, arg UpdateCreditLegParams) (int64, error)
	UpdateDebitLeg(ctx context.Context, arg UpdateDebitLegParams) (int64, error)
	UpdateOutboxStatus(ctx context.Context, arg UpdateOutboxStatusParams) error
	UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) error
}

var _ Querier = (*Queries)(nil)
