// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

type Querier interface {
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (pgconn.CommandTag, error)
	GetTransaction(ctx context.Context, transactionID string) (Transaction, error)
	IncrementRetryCount(ctx context.Context, transactionID string) error
	UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
