// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: txn_queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :execresult
INSERT INTO transactions (
    transaction_id, 
    payer_account_id, 
    payee_account_id, 
    amount, 
    status
) VALUES (
    $1, $2, $3, $4, $5
) ON CONFLICT (transaction_id) DO NOTHING
`

type CreateTransactionParams struct {
	TransactionID  string `json:"transaction_id"`
	PayerAccountID string `json:"payer_account_id"`
	PayeeAccountID string `json:"payee_account_id"`
	Amount         int64  `json:"amount"`
	Status         string `json:"status"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, createTransaction,
		arg.TransactionID,
		arg.PayerAccountID,
		arg.PayeeAccountID,
		arg.Amount,
		arg.Status,
	)
}

const getTransaction = `-- name: GetTransaction :one
SELECT transaction_id, payer_account_id, payee_account_id, amount, status, retry_count, bank_reference_id, failure_reason, created_at, updated_at FROM transactions
WHERE transaction_id = $1 LIMIT 1
`

func (q *Queries) GetTransaction(ctx context.Context, transactionID string) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, transactionID)
	var i Transaction
	err := row.Scan(
		&i.TransactionID,
		&i.PayerAccountID,
		&i.PayeeAccountID,
		&i.Amount,
		&i.Status,
		&i.RetryCount,
		&i.BankReferenceID,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementRetryCount = `-- name: IncrementRetryCount :exec
UPDATE transactions
SET 
    retry_count = retry_count + 1,
    updated_at = NOW()
WHERE transaction_id = $1
`

func (q *Queries) IncrementRetryCount(ctx context.Context, transactionID string) error {
	_, err := q.db.Exec(ctx, incrementRetryCount, transactionID)
	return err
}

const updateTransactionStatus = `-- name: UpdateTransactionStatus :execrows
UPDATE transactions 
SET 
    status = $2, 
    bank_reference_id = COALESCE($3, bank_reference_id),
    failure_reason = COALESCE($4, failure_reason),
    updated_at = NOW()
WHERE transaction_id = $1
`

type UpdateTransactionStatusParams struct {
	TransactionID   string      `json:"transaction_id"`
	Status          string      `json:"status"`
	BankReferenceID pgtype.Text `json:"bank_reference_id"`
	FailureReason   pgtype.Text `json:"failure_reason"`
}

func (q *Queries) UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTransactionStatus,
		arg.TransactionID,
		arg.Status,
		arg.BankReferenceID,
		arg.FailureReason,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
